### ISSUE TITLE
Xác minh do hoang mang ✌️ 

### ISSUE THREAD

**Issue by huuhait** [nhubaotruong/league-of-legends-linux-garena-script#1]
Do mình không có thời gian test :v 
có thật script của bạn chạy được leage of legends của garena hông bạn?

cảm ơn bạn nhiều nha

**Comment by nhubaotruong** [comment]
Tác dụng của script này là bắt cái process RiotServices.exe của LOL, extract Garena Token, xong relaunch lại game với cái garena token thôi. Công sức chính là nhớ cộng đồng lutris cả :v

**Comment by nhubaotruong** [comment]
Mình chơi được 3 tháng dùng cách này rồi bạn :v . Trước đây khổ râm hơn, dùng máy ảo để lấy Garena token :v

**Comment by huuhait** [comment]
pro đấy bạn
trước mình cũng tính lấy token nhưng k biết p làm sao
tks b nhiều nha <3
