### ISSUE TITLE
The lol.py script is no longer needed with the new wine-lol version

### ISSUE THREAD

**Issue by hi563145** [nhubaotruong/league-of-legends-linux-garena-script#13]
I don't know how github work for this kinda of thing but I just want to say the if you are using the lutris-ge-lol you can just use that wine version and launch the garena client with it and it will work. Do keep in mind you still need launchhelper.sh but I never really tested without it, so feel free to try.
https://teddit.net/r/leagueoflinux/comments/plzb3x/great_news_for_garena_players_repost/

**Comment by nhubaotruong** [comment]
I'm not sure about this. You can try if that works. As for me, I'm in a limited connection area and have to use mobile internet. I cannot even update the game :disappointed:  . Sorry I cannot test it myself now

**Comment by VihagChaturvedi** [comment]
@hi563145 I have cited issues with how it doesn't work as of rn

I have raised a request recently as to how it isn't completely working yet.

Essentially, Wine and Garena are acting funny which is leading to next to no communication b/w client and garena servers. In the same post as that, I have mentioned that issue.

[Also check out my reddit post regarding the same](https://www.reddit.com/r/leagueoflinux/comments/po7io4/potentially_new_issue_ux_doesnt_fully_load_and/)

**Comment by VihagChaturvedi** [comment]
@nhubaotruong if possible, can u preserve the current launchhelper.sh u have rn? i think we need to keep it

**Comment by hi563145** [comment]
@VihagChaturvedi I don't have this issue it just works for me. I ran into that issue once and it is when I am connected to a vpn. I am a complete noob here but I have theory. Previously I we launch the game using the garena token. The garena token only last for like 5 minutes. So my theory is the token might have expired as it takes too long for your computer to connect to the port or something which is what the launchhelper is doing.

**Comment by VihagChaturvedi** [comment]
The Garena token is needed for client-server connection while playing, after the connection has been established, the token isn't needed(ie when u are actually playing)

And no, the config file doesn't add any arguments in the Runner Options, so I believe it isn't creating a token at all.

Previously, u didn't need lol-ge-6.16-2, the Garena script (aka this repo), handled only the launching LoL part.

Networking was never an issue.

**Comment by VihagChaturvedi** [comment]
Also, the script is free to vet, so I believe the better solution would be to add the .py as a launch script while keeping the older runner

Atleast until the current 6.16-2 runner is figured out

**Comment by nhubaotruong** [comment]
Hi @hi563145 , indeed Garena will not connect when using a VPN, we can't do anything about it

**Comment by nhubaotruong** [comment]
@VihagChaturvedi Here's the current `launcherhelper.sh` that I have on my system
```bash
#!/bin/bash
$(dirname "$0")/syscall_check.sh
process=LeagueClientUx.exe
uxpid=$(timeout 4m sh -c "until pidof ${process}; do sleep 1; done")
if [[ ! -n $uxpid ]]; then
  echo "Could not find process ${process}"
  exit 1
fi
echo "LeagueClientUx pid: ${uxpid}"
port=$(xargs -0 < /proc/${uxpid}/cmdline \
  | sed -n 's/.*--app-port=\([[:digit:]]*\).*/\1/p')
if [[ ! -n $port ]]; then
  echo "Could not find port"
  exit 1
fi
echo "Waiting for port ${port}"

kill -STOP ${uxpid}
timeout 5m /bin/bash -c "
until openssl s_client -connect :${port} <<< Q > /dev/null 2>&1; do
  sleep 1
done"
kill -CONT ${uxpid}
```

**Comment by VihagChaturvedi** [comment]
Oh u are back home? @nhubaotruong

**Comment by nhubaotruong** [comment]
Yes, I just got back in the morning

**Comment by VihagChaturvedi** [comment]
yay we can get back at fixing stuff now

**Comment by VihagChaturvedi** [comment]
god this IS A PAIN THE ASS

**Comment by VihagChaturvedi** [comment]
ok i think this is an issue on my end

```
[0923/232208:ERROR:network_change_notifier_win.cc(153)] WSALookupServiceBegin failed with: 8
```

i am not sure where to start, WineHQ forums don't seem to have much info

**Comment by nhubaotruong** [comment]
Did you use the script to launch the game ? I started just fine last night ?

**Comment by VihagChaturvedi** [comment]
Turns out it is some sort of "out of memory" issue, according to a guy in Linux Gaming discord server

Not a VPN thing, ig

**Comment by nhubaotruong** [comment]
It's weird how this is an "out of memory" issue though
