### ISSUE TITLE
Under "Alternative Method for Installing LoL", "English" version should be noted as Singapore version

### ISSUE THREAD

**Issue by sleeping-miyagi** [nhubaotruong/league-of-legends-linux-garena-script#16]
Under "Alternative Method for Installing LoL", "English" version should be noted as "Singapore" version instead. The link provided is for the Singapore version and not an "English" version. This should be clarified as it could be confusing for some Garena players who are on the "Philippines" version (which is also in English) and might download this instead, thinking it will work on the Philippine Garena server.

Here is a link to the Philippine version to distinguish from Singapore version: https://lol.garena.ph/download

Thanks.

**Comment by VihagChaturvedi** [comment]
Noted.

Thanks a lot, if you wish u can create a MR regarding the same.

Otherwise, @nhubaotruong can fix it later on

**Comment by nhubaotruong** [comment]
I've updated to include all possible Garena region download link. If that's okay to you then we'll close this issue :smile:

**Comment by sleeping-miyagi** [comment]
Thanks. This is good!
