### ISSUE TITLE
Unable to install Garena

### ISSUE THREAD

**Issue by redironman5** [nhubaotruong/league-of-legends-linux-garena-script#17]
![Screenshot_2021-10-07_23-05-14](https://user-images.githubusercontent.com/92115524/136435348-ea4a0db4-2166-4b55-b4f8-cd151726f0c5.png)

Getting this error while attempting to install Garena even though I have lutris ge lol installed in runners.

PS.  First time github and linux user, if my application format is wrong or something or if you want any additional data from my computer by running commands in terminal, please let me know.

**Comment by nhubaotruong** [comment]
If update through Garena didn't work, try downloading LOL manually. The guides are in the front page of this repo :smile:

**Comment by VihagChaturvedi** [comment]
@redironman5 we recognize the 89% issue, had it happen to me as well

which is also why we have mentioned an alternative install method on the front page, the way works for me.

**Comment by redironman5** [comment]
no no no the screenshot is from the alternate method of installation.  I downloaded the game directly from the website, extracted it, ran the .exe inside wine but the game is not locating the installed files.

**Comment by nhubaotruong** [comment]
Can you provide a video of you doing the manual adding of LOL :thinking: ?

**Comment by VihagChaturvedi** [comment]
Will look into it tomorrow, a bit lage here

**Comment by VihagChaturvedi** [comment]
Yes yes will do.

Yasuo mains literally give me nightmares so imma try

**Comment by redironman5** [comment]
ah no, i reinstalled in a different folder named "garenalol" and it still didnt work.  For your reference, this manual installation method actually worked flawlessly before this patch.  I've only been experiencing this problem after the new patch release.

**Comment by VihagChaturvedi** [comment]
Wait how old is the patch again? I havent been on since 3-4 days

**Comment by VihagChaturvedi** [comment]
I dont have access to my computer atm.

But this does seem like a pretty major problem

**Comment by nhubaotruong** [comment]
Garena has a `Region` selection in settings, did you choose your correct region ?

**Comment by nhubaotruong** [comment]
Maybe Garena fucked up and they silently fix it, anyway no way to know for sure now :sweat_smile:

**Comment by redironman5** [comment]
Yeah i wish we had figured out whats the issue.  Now we don't know what caused it and what rectified it. Lol.

**Comment by VihagChaturvedi** [comment]
wait the issue is fixed?

i didnt even get to test it ;-;
