### ISSUE TITLE
Start League of Legend by other locate 

### ISSUE THREAD

**Issue by nguyenhai97** [nhubaotruong/league-of-legends-linux-garena-script#18]
How can I change locate, for example switch to vi_VN or ja_JP locate when starting the game? also there seem to be some font issue with garena and League client, is there a way to by pass that?

**Comment by nhubaotruong** [comment]
For font, what distro are you using ?

**Comment by nguyenhai97** [comment]
That strange because I already set garena language to Vietnamese yet it still launch with English interface. For font I'm using fedora workstation f34

**Comment by nhubaotruong** [comment]
Let me check language later when I get back home, try installing msfonts to prevent font issue https://www.fosslinux.com/42406/how-to-install-microsoft-truetype-fonts-on-fedora.htm

**Comment by nguyenhai97** [comment]
About the font issue, just double check the client and found that language setting right next to the Play button, will try install msfont now

**Comment by nguyenhai97** [comment]
Yeah, for the most part it work well. Only annoyed by the long start up time 3-5 min and the delay after a match is finished

**Comment by nguyenhai97** [comment]
some time the game won't work after a match and fan run like hell when playing. I mean I play World of Tank before and it not even that cpu hunggry

**Comment by nhubaotruong** [comment]
Too bad I cannot do anything about it, Garena has some modification to LOL :disappointed:

**Comment by nguyenhai97** [comment]
yeah, f u garena =)) I will close this issue for now
