### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by neverloses87** [nhubaotruong/league-of-legends-linux-garena-script#2]
Could you provide the path where your Garena and League are installed, respectively?

I've read your python script and guessed that you installed them under the same directory (i.e. ~/Games/league-of-legends). However, it doesn't work when I intend to do so, the one installed latter are not able to start (perhaps not configured or somehow)?

Thanks.

**Comment by nhubaotruong** [comment]
Actually it doesn't have to be in the same folder. But there's something I always forget myself, that is this step: https://github.com/nhubaotruong/league-of-legends-linux-garena-script#config-lol-lutris
Please double check if you have pointed the Executable to `RiotClientServices.exe` yet

**Comment by nhubaotruong** [comment]
Btw I installed Garena in `~/Games/Garena`, and LOL in `~/Games/league-of-legends`

**Comment by neverloses87** [comment]
It somehow worked, I just have to wait for like 2 minutes after running the script.

I'd like to read the code more carefully and find out if any optimization could be done.

Thanks a lot!!

**Comment by nhubaotruong** [comment]
The script stop after it launches LOL, the long waiting time is because of LOL itself, so I don't think anything could be done here tbh 😁
