### ISSUE TITLE
session keeps expiring

### ISSUE THREAD

**Issue by kaeelaz** [nhubaotruong/league-of-legends-linux-garena-script#23]
I don't know whether this is normal for all but I need to keep logging in after evrery game I play. I followed the guide and the in-game actually worked flawlessly. the first launch of client is also okay(completely loads within minute) but the session expires mid game and although it does not affect my in-game the next launch takes quite a bit of time or does not load at all at times. Sorry for not including any logs(I'm also new to linux).

**Comment by nhubaotruong** [comment]
Weird, are you sharing your account with someone else and he/she is logging in while you're playing ?

**Comment by kaeelaz** [comment]
> Weird, are you sharing your account with someone else and he/she is logging in while you're playing ?

Not really, however there was one time when I played a tft game first and then a normal game next. The session did not expire at that time. And the problem has never happened on windows. Hypothetically, if someone was using my account(without me knowing), The session would have expired in windows too right?

**Comment by nhubaotruong** [comment]
This is not something I've personally faced. Can you right click to Garena and LOL in lutris and select `show log` (after you have started both app) on both side, and the next time you have that issue, please upload the log at the time for me please ?

**Comment by kaeelaz** [comment]
Okay, somehow it fixed itself. apparently now it only happens like 2 out of 10 times. If I don't close the league client at all(when there is no issue with the session expiring) the issue never occurs until the next launch(which happens rarely now).

**Comment by kaeelaz** [comment]
tarted initial process 10984 from /home/kaeelaz/.local/share/lutris/runners/wine/lutris-6.14-4-x86_64/bin/wine /home/kaeelaz/Games/garena/drive_c/Program Files (x86)/Garena/Garena/Garena.exe
Start monitoring process.
esync: up and running.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[1111/214434:ERROR:network_change_notifier_win.cc(153)] WSALookupServiceBegin failed with: 8
[1111/214452:ERROR:ipc_channel_win.cc(502)] pipe error: 232
[1111/214452:ERROR:ipc_channel_win.cc(502)] pipe error: 232
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

**Comment by nhubaotruong** [comment]
There isn't anything wrong here, is the problem still persist for you ?
