### ISSUE TITLE
Upon launching the garena menu only has white screen

### ISSUE THREAD

**Issue by nzrt-pm** [nhubaotruong/league-of-legends-linux-garena-script#24]

**Comment by nhubaotruong** [comment]
Can you provide some screenshot, have you uncheck the option "Use proxy while viewing news" ?

**Comment by nzrt-pm** [comment]
Solry for the late response. Managed to fix it, I reinstalled wine-mono and the wine-mono-gecko-version-fix from the aur.

**Comment by nhubaotruong** [comment]
This shouldn't be necessary, but if it works for you then it's a valid fix :+1:
