### ISSUE TITLE
script for config lol executable not work and game glitches :(

### ISSUE THREAD

**Issue by tienbuigia** [nhubaotruong/league-of-legends-linux-garena-script#26]
for the script I configed manually and it works and I can go to practice tool, high FPS, everything seems good.
But when I started attacking a dummy the game glitches, stop attacking, game's good again. (FPS is stable)

I'm currently using elementaryOS now (I used arch-based before)
CPU: i3-9100f
GPU: AMD RX570
What I've done: 
1. Turn off DXKV = not works
2. Choose DX9 = not works

**Comment by nhubaotruong** [comment]
I'm gonna need more info
- What's the AMD driver are you running. amdgpu ?
- Are you using deb lutris or flatpak lutris ?
- Any lutris log you can provide ?

**Comment by tienbuigia** [comment]
It works flawlessly now after I restarted my system (It not works before)
Thanks for the fast reply!
