### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Miho1254** [nhubaotruong/league-of-legends-linux-garena-script#28]
miho@Miho:~/Downloads$ ./lol-x86_64.AppImage
/tmp/.mount_lol-x8hRIol6/lol.sh: 6: sqlite3: not found
The script will wait for a RiotClientServices.exe process to show up to get it's token. So go to the Garena client and press Play
/tmp/.mount_lol-x8hRIol6/lol.sh: 9: [[: not found
/tmp/.mount_lol-x8hRIol6/lol.sh: 12: [[: not found

**Comment by nhubaotruong** [comment]
What distro are you using, I thought `sqlite3` is available on all distro =((

**Comment by Miho1254** [comment]
> 

ubuntu 20.04

**Comment by nhubaotruong** [comment]
My bad, should have bundled sqlite3 in the AppImage as well, can you please run 
```
sudo apt install sqlite3
```
then try again please

**Comment by Miho1254** [comment]
> My bad, should have bundled sqlite3 in the AppImage as well, can you please run
> 
> ```
> sudo apt install sqlite3
> ```
> 
> then try again please

/tmp/.mount_lol-x8b1P0fx/lol.sh: 26: [[: not found
/tmp/.mount_lol-x8b1P0fx/lol.sh: 32: [[: not found
still get this

**Comment by nhubaotruong** [comment]
Wait a bit, I'm fixing it

**Comment by nhubaotruong** [comment]
Hi @Miho1254 , please download the latest AppImage and try again https://github.com/nhubaotruong/league-of-legends-linux-garena-script/releases/tag/v2

**Comment by Miho1254** [comment]
> Hi @Miho1254 , please download the latest AppImage and try again https://github.com/nhubaotruong/league-of-legends-linux-garena-script/releases/tag/v2

when i done all things i got this
![Screenshot from 2022-01-27 13-33-23](https://user-images.githubusercontent.com/83270073/151304695-5b02a1f1-3c7a-4afb-9fce-a1dd779b5bc5.png)
![Screenshot from 2022-01-27 13-33-43](https://user-images.githubusercontent.com/83270073/151304708-87cc270d-67e6-491c-bdc1-c5499638c772.png)

**Comment by nhubaotruong** [comment]
Yep, it's working, the client performance is pretty slow, not as fast as windows. You can open the `System Monitor` app and check if `LeagueClient.exe` and `RiotClientServices.exe` are running. It should open in about 2-5 mins. There's nothing I can do about this slowness :((

**Comment by Miho1254** [comment]
> Yep, it's working, the client performance is pretty slow, not as fast as windows. You can open the `System Monitor` app and check if `LeagueClient.exe` and `RiotClientServices.exe` are running. It should open in about 2-5 mins. There's nothing I can do about this slowness :((

so i have to wait for it?

**Comment by nhubaotruong** [comment]
Yes, you just have to wait. But like I said, check the processes to make sure

**Comment by nhubaotruong** [comment]
@Miho1254 So does it work for you ?
