### ISSUE TITLE
Cannot do config

### ISSUE THREAD

**Issue by iamdjhayzt** [nhubaotruong/league-of-legends-linux-garena-script#29]
Hello!

First of all, thank you for your work on Garena based LoL. Its a pain for us SEA tbh. I've been using your git ever since I transferred to Linux and been distro hopping ever since. I see you've updated your git and made an appimage for most of the work. I'm currently stuck on config atm and I don't know what to do here. Can you help me? Thanks!

![image](https://user-images.githubusercontent.com/70418264/151474237-65ca063f-df55-4735-b9c4-07dc6f75d899.png)

**Comment by nhubaotruong** [comment]
Hi, sorry for the inconvenience, I've updated the AppImage https://github.com/nhubaotruong/league-of-legends-linux-garena-script/releases/tag/v3. Please try again

**Comment by nhubaotruong** [comment]
Also I haven't tested my script on fish shell yet, so if it doesn't work, please let me know again

**Comment by iamdjhayzt** [comment]
Looks like I have a different error now

![image](https://user-images.githubusercontent.com/70418264/151475949-817fd596-e2a7-44c0-b6aa-0eef7f60d9ce.png)

**Comment by iamdjhayzt** [comment]
> Also I haven't tested my script on fish shell yet, so if it doesn't work, please let me know again

Looks like a new error has appeared. I tried with sudo and it doesn't work too.

![image](https://user-images.githubusercontent.com/70418264/151476104-63b6a1af-394d-45b1-b34e-729b1c372417.png)

**Comment by nhubaotruong** [comment]
You forgot to give it execute permission LOL
chmod +x lol-x86_64.AppImage

**Comment by iamdjhayzt** [comment]
> You forgot to give it execute permission LOL chmod +x lol-x86_64.AppImage

Haaaaallllllleeeelluujaah! Thanks bro!
![image](https://user-images.githubusercontent.com/70418264/151478290-cf124883-4dd1-4b2a-bfca-c7000a4f70fe.png)

**Comment by nhubaotruong** [comment]
Has it started yet, it usually takes a reaaaaaaly long time, like 5 mins to start

**Comment by iamdjhayzt** [comment]
> Has it started yet, it usually takes a reaaaaaaly long time, like 5 mins to start

Yeah I'm actually immune to it already. Lel. Btw, do you recommend using Fsync?

**Comment by nhubaotruong** [comment]
If it doesn't break anything, why not. I've actually not seen much different with Fsync on LOL, maybe because it's already isn't optimized for Linux

**Comment by nhubaotruong** [comment]
I'll close this issue for now, since it is resolved
