### ISSUE TITLE
Riot Client vs League Client

### ISSUE THREAD

**Issue by abiswas97** [nhubaotruong/league-of-legends-linux-garena-script#3]
Not an issue, but a difference between the two. I started with the Riot Client exe as suggested in the README, but league took about 4 mins to load and the champ select chat loaded around 5+ seconds late. 

Using the League Client shortened the load time by half, and entering the chat is almost immediate. Maybe this could help improve the long load times.

**Comment by nhubaotruong** [comment]
Can you tell me what region are you playing in ?

Also can you tell me the exact program name, I tried League Client before but it wasn't able to load user profile

**Comment by nhubaotruong** [comment]
I just tried it, WOW it's fast. 

Thanks for your suggetion, I'll update the script

**Comment by nhubaotruong** [comment]
The reason I used **RiotClientServices.exe** because I saw it on a reddit post, and from personal tries before **LeagueClient.exe** just got error fail to load user profile. Now it works better then we should all be using **LeagueClient.exe**

**Comment by abiswas97** [comment]
I'm using the Singapore server, and it's been really smooth from my tries today. Glad this helped and worked in your case too! Hopefully this makes the Garena client more accessible

**Comment by nhubaotruong** [comment]
Thank you so much. If you don't have any other comment, please close this issue 😁
