### ISSUE TITLE
The config script is broken

### ISSUE THREAD

**Issue by drshapeless** [nhubaotruong/league-of-legends-linux-garena-script#31]
I followed the guide to use this command, `./lol-x86_64.AppImage config`, it gives this error, `Error: stat : no such file or directory`.

I then tried to manually edit the executable path to the RiotClientServices.exe. 

But I have trouble launching the script via `./lol-x86_64.AppImage`. It can't even find the wine version I am using. Do I have to configure anything in the runner options in Garena other than in League of Legends? I changed the wine version to lutris-ge-lol.7.0 in both lol and garena runner options.

I am using Arch.

I used to play league with your older python script, but after the lutris-ge-lol update, I was able to play without script. But that is broken today. And I have reinstalled, reboot and tried different wine versions for hours. And still doesn't have any progress.

Does anyone successfully play lol at the moment?

**Comment by nhubaotruong** [comment]
I'm gonna need more info on your config. My setup is using two wineprefixes, not one.
- For Garena it's just gonna launch the Garena client
- For LOL it will point to Garena's installed version of LOL like in the picture
![image](https://user-images.githubusercontent.com/28810481/152275386-ff9870c1-e22c-4b8c-82c2-f3beb717f134.png)

Can you share yours ?

**Comment by drshapeless** [comment]
Sure, but how do I add wineprefixes manually since the script is not working?
![2022-02-03_113153](https://user-images.githubusercontent.com/66210497/152277111-fc62653d-2677-43b1-a1ca-3f175be9780d.png)

**Comment by nhubaotruong** [comment]
Do you have discord ? Can we call and share with me what's going on, your config is correct already

**Comment by drshapeless** [comment]
Sure, `jky#3886`. I am free to talk now.

**Comment by drshapeless** [comment]
The broken config option is due to a duplicated installation of league in lutris, thus kind of corrupted the db that the script need to check, after manually remove the excess row in the db, the config script is working.

However, I am still not able to play league due weird unsolved issues. But the config is not broken, thanks @nhubaotruong for his time.
