### ISSUE TITLE
Pop up not working to modify wine in Ubuntu.

### ISSUE THREAD

**Issue by tazihad** [nhubaotruong/league-of-legends-linux-garena-script#32]
I run garena lol successfully last night on Debian Plasma. But with Plasma I had some graphics issue. Mainly due to kwin compositor.
So, I fresh installed Ubuntu 20.04. Did every step. Every thing is working. But the pop up that was supposed to modify wine for every reboot isn't popping. So, league launcher crash after few minute. Is there something wrong?
I have wine version wine-7.0 on local system. As well as latest wine-lutris-lol-7-ge.

**Comment by nhubaotruong** [comment]
Can you share the lutris log/terminal output/lutris config please

**Comment by nhubaotruong** [comment]
Closing due to no reply, feel free to reopen
