### ISSUE TITLE
Can't go to match

### ISSUE THREAD

**Issue by Kalserl** [nhubaotruong/league-of-legends-linux-garena-script#34]
I install follow your instruction, but after choosing champion and loading to the match, it seem crack and I have no idea about reason.  Do you have any solution ?
I use archcraft OS.
![Screenshot_2022-03-05-06-27-11_1920x1080](https://user-images.githubusercontent.com/96782353/156881755-dee784e3-7703-46ba-b360-790dd72e32ae.png)
![Screenshot_2022-03-05-06-45-17_1920x1080](https://user-images.githubusercontent.com/96782353/156881760-32769728-7541-4bf4-8bdc-1807a6266768.png)
![Screenshot_2022-03-05-06-44-08_1920x1080](https://user-images.githubusercontent.com/96782353/156881895-b3075806-924d-4bd8-90fb-82190ad9801c.png)

**Comment by Kalserl** [comment]
This is some infomation on my lutris settin
![Screenshot_2022-03-05-09-48-02_1920x1080](https://user-images.githubusercontent.com/96782353/156888991-43d73d9d-a687-4006-aca6-cf2d05d6f5f8.png)
![Screenshot_2022-03-05-09-48-15_1920x1080](https://user-images.githubusercontent.com/96782353/156888995-a0e2cc27-b143-420f-954c-bdb93db4284b.png)
![Screenshot_2022-03-05-09-48-28_1920x1080](https://user-images.githubusercontent.com/96782353/156888996-9d0ee9d1-4722-44ca-b675-6118fe2f38b8.png)
![Screenshot_2022-03-05-09-48-35_1920x1080](https://user-images.githubusercontent.com/96782353/156888997-b6055463-47d7-41a6-b498-3a85fa1b2f12.png)
![Screenshot_2022-03-05-09-48-40_1920x1080](https://user-images.githubusercontent.com/96782353/156889000-2a016c34-99c9-413f-9fe0-496f188c0e13.png)
![Screenshot_2022-03-05-09-48-55_1920x1080](https://user-images.githubusercontent.com/96782353/156889005-1e1b249c-dac8-4ad1-9b66-36797c9f5929.png)
![Screenshot_2022-03-05-09-49-07_1920x1080](https://user-images.githubusercontent.com/96782353/156889008-7fe92bc4-c145-4390-83b6-d05cd2abfc00.png)
![Screenshot_2022-03-05-09-51-08_1920x1080](https://user-images.githubusercontent.com/96782353/156889011-4739e793-55be-46cc-b6e8-e34134f1d59a.png)
![Screenshot_2022-03-05-09-51-13_1920x1080](https://user-images.githubusercontent.com/96782353/156889013-7f4b8b63-3277-4be3-a6b8-89cec87c132c.png)
![Screenshot_2022-03-05-09-52-55_1920x1080](https://user-images.githubusercontent.com/96782353/156889017-0b5a4c3f-8b9f-4775-955d-3e63b36a64ae.png)
g

**Comment by nhubaotruong** [comment]
The executable is supposed to be `.../32787/Riot Client/RiotClientServices.exe`. Please try it. 

Nice WM btw

**Comment by Kalserl** [comment]
I set the executable like you said, change game directory to C:/, set game directory back to default, even reinstall games, but nothing change. I can go to client normally but It still crack when I tried to load to the match.
I'm install all package in your instruction. I update all of them to newest version at least now.
![Screenshot_2022-03-06-06-33-03_1920x1080](https://user-images.githubusercontent.com/96782353/156921922-0b7e3fa9-2be0-4e8b-bfcc-c6aca37b6db7.png)
![Screenshot_2022-03-06-06-55-34_1920x1080](https://user-images.githubusercontent.com/96782353/156921965-1043bcc1-5198-4fa4-bae1-339bbe3fbe08.png)

![Screenshot_2022-03-07-03-56-14_1920x1080](https://user-images.githubusercontent.com/96782353/156999356-345ed35e-38bc-4a1d-ae1f-6796f70f9264.png)

**Comment by nhubaotruong** [comment]
Can I contact you anywhere else, I'm afraid this isn't gonna be solved through github, it's pretty weird case

**Comment by SscSPs** [comment]
This same was happening with me as well, but after the latest update, the game is not even opening, 
Garena opens just fine, after that when I run the appimage to run the interseptor and then click play, nothing shows up.


here are the lutris logs starting from when I open the appimage:

```
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
2022-03-09 13:59:56,748: Using NVIDIA drivers 510.54 for x86_64
2022-03-09 13:59:56,748: GPU: Unknown
2022-03-09 13:59:56,748: GPU: 1002:1638 17AA:3AAE (amdgpu drivers)
2022-03-09 13:59:56,748: GPU: 10DE:25E2 17AA:3AAE (nvidia drivers)
2022-03-09 13:59:56,872: Running /data/personal/linux_game_1/launchhelper.sh in the background
Started initial process 96246 from gamemoderun /home/sahil/.local/share/lutris/runners/wine/lutris-ge-lol-7.0-1-x86_64/bin/wine /data/personal/linux_games/drive_c/Games/32771/Riot Client/RiotClientServices.exe --garena-plus-token=CechRZ9jFSih5Wx71C6Cs3mGQ4s60CDwdva6hJAeUiTXJ0yFOcvq17RCME2nN/W0+TDksvFGb7t8MkrlBurPBQ7XFtJ1v9nE7UuB1AL04Ea5AWYst0N89w+Mnt+EcLCF08X+OtpXcnv21WuMw3etAAGM5TZAbrbUD4xm3sncPrOPdM5V0UaD8u/X2vECnsVPzOOMW6tGUgkPrIyrgm/oxxXi37SLOFfTBKZgsDQC0oLtA0UtHcBlXr4MZI+TNSKIA0ojK4VkXzq/9mFUcXcieSIpuWg9393l7ms0De6vDl+Wc+F/8+J+yo/sxgjvPkbLWR39AJzC1P9DyFaPce8Y8Q== --region=SG -- --locale=en_SG --landing-token=d65d07eb07f1db96b415380871c7a7da930dc469074e4d1295968eec1e7f8185 --servers.chat.chat_host=sg1.chat.si.riotgames.com --servers.lcds.lcds_host=prod.lol.garenanow.com --servers.lcds.login_queue_url=https://lq.lol.garenanow.com/login-queue/rest/queues/lol --region=SG --parent-client=GarenaPC
Start monitoring process.
Started initial process 96247 from /data/personal/linux_game_1/launchhelper.sh
Start monitoring process.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
esync: up and running.
zenity: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: gst_element_request_pad_simple
zenity: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: gst_element_request_pad_simple
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
Caught signal 15
Killing PID 96247 with SIGTERM
Killing PID 96264 with SIGTERM
Killing PID 96265 with SIGTERM
Killing PID 97549 with SIGTERM
--terminated processes--
Monitored process exited.
Initial process has exited (return code: 15)
All processes have quit
Exit with return code 15
2022-03-09 14:03:22,515: Running /data/personal/linux_game_1/launchhelper.sh in the background
Started initial process 97561 from gamemoderun /home/sahil/.local/share/lutris/runners/wine/lutris-ge-lol-7.0-1-x86_64/bin/wine /data/personal/linux_games/drive_c/Games/32771/Riot Client/RiotClientServices.exe --garena-plus-token=CechRZ9jFSih5Wx71C6Cs3mGQ4s60CDwdva6hJAeUiTXJ0yFOcvq17RCME2nN/W0+TDksvFGb7t8MkrlBurPBQ7XFtJ1v9nE7UuB1AL04Ea5AWYst0N89w+Mnt+EcLCF08X+OtpXcnv21WuMw3etAAGM5TZAbrbUD4xm3sncPrOPdM5V0UaD8u/X2vECnsVPzOOMW6tGUgkPrIyrgm/oxxXi37SLOFfTBKZgsDQC0oLtA0UtHcBlXr4MZI+TNSKIA0ojK4VkXzq/9mFUcXcieSIpuWg9393l7ms0De6vDl+Wc+F/8+J+yo/sxgjvPkbLWR39AJzC1P9DyFaPce8Y8Q== --region=SG -- --locale=en_SG --landing-token=d65d07eb07f1db96b415380871c7a7da930dc469074e4d1295968eec1e7f8185 --servers.chat.chat_host=sg1.chat.si.riotgames.com --servers.lcds.lcds_host=prod.lol.garenanow.com --servers.lcds.login_queue_url=https://lq.lol.garenanow.com/login-queue/rest/queues/lol --region=SG --parent-client=GarenaPC
Start monitoring process.
Started initial process 97562 from /data/personal/linux_game_1/launchhelper.sh
Start monitoring process.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
esync: up and running.
zenity: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: gst_element_request_pad_simple
zenity: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: gst_element_request_pad_simple
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
```

**Comment by SscSPs** [comment]
If its relevant, I use the same files on windows as well, I have a dual-boot system and I have the game files on btrfs partition, I use https://github.com/maharmstone/btrfs to mount the partition and run garena lol form the same files

**Comment by Kalserl** [comment]
> Can I contact you anywhere else, I'm afraid this isn't gonna be solved through github, it's pretty weird case

You can contract me though twitter or messenger, this is my twitter and facebook account:
https://twitter.com/Evergarden299
https://www.facebook.com/kaka.mada.9843

**Comment by nhubaotruong** [comment]
Hi @SscSPs, I've update a fix on the main github link, please follow it and give me some feedback :rocket:

**Comment by thanhbtheo11** [comment]
Anh có thể cho em xin liên lạc để hỏi 1 số cái lỗi khi bấm chơi LOL không ạ ^^

**Comment by nhubaotruong** [comment]
@thanhbtheo11 link fb nha b https://m.facebook.com/nhubaotruong

**Comment by nhubaotruong** [comment]
I'm gonna close this since there's no reply. Feel free to reopen
