### ISSUE TITLE
lutris flatpak support

### ISSUE THREAD

**Issue by tazihad** [nhubaotruong/league-of-legends-linux-garena-script#35]
This doesn't work if I install Lutris through flathub beta. I am using Fedora Silverblue. So, Flatpak is my only option. could you release appimage for flatpak lutris?
I guess it would be also be helpful for people who are using Steam Deck.

**Comment by nhubaotruong** [comment]
Currently it's not possible to play with flatpak because of this issue: https://github.com/flathub/net.lutris.Lutris/issues/85

Lutris does offer a tar ball download. You can try that in the home directory, it's not clean, but better than nothing since I can't find any appimage version of lutris

**Comment by tazihad** [comment]
@nhubaotruong I have faced exactly that error when installing Garena in lutris flatpak.
modify_ldt error.

**Comment by nhubaotruong** [comment]
Since you're using silverblue, I guess custom compile flatpak is not an option. Have you try the tar ball download from https://lutris.net/downloads ?

**Comment by VihagChaturvedi** [comment]
@tazihad Flatpaks don't allow modifiying LDTs as this has security issues

Flatpak Lutris is not suitable yet, it is better to download and the rpm-ostree version

try `rpm-ostree install lutris` and that should work. if not, report back with logs
