### ISSUE TITLE
pls update not working

### ISSUE THREAD

**Issue by zihadio** [nhubaotruong/league-of-legends-linux-garena-script#36]
game crash after league logo

**Comment by nhubaotruong** [comment]
I am aware of this, but I haven't found a way for it work on Garena yet. I'll notify if I found a fix

**Comment by S1DRAA** [comment]
same issue here

**Comment by Arman05** [comment]
launcher keeps like this :

[https://drive.google.com/file/d/1DIlAsoXqypXJog1iMim2LPJTy76ofveS/view?usp=sharing](url)

Error:

`Started initial process 15521 from gamemoderun /home/myuser/.local/share/lutris/runners/wine/lutris-ge-lol-7.0-2-x86_64/bin/wine/home/user/Games/garena/drive_c/Garena/Games/32771/Riot Client/RiotClientServices.exe --garena-plus-token=__my_token___== --region=SG -- --locale=en_SG --landing-token=7110b6ff1ff22836b90f24ced6c72cda0da8f620a8bd098f074a1993c2ad56fa --servers.chat.chat_host=sg1.chat.si.riotgames.com --servers.lcds.lcds_host=prod.lol.garenanow.com --servers.lcds.login_queue_url=https://lq.lol.garenanow.com/login-queue/rest/queues/lol --region=SG --parent-client=GarenaPC
Start monitoring process.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
esync: up and running.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

**Comment by nhubaotruong** [comment]
@zihaaad @S1DRAA It's working on my side now without any modification, can you try again ?

**Comment by manhuyhong** [comment]
It's working for me now, but only on the first time after each boot. If I close the game and start again, it won't work (logo disappears and nothing happens) until I reboot my PC. So basically, I have to reboot every time I want to play. Not a big problem, just a little inconvenient. Maybe because I messed up somewhere lol.
