### ISSUE TITLE
Can't install league of legends

### ISSUE THREAD

**Issue by utbuiquoc** [nhubaotruong/league-of-legends-linux-garena-script#42]
![image](https://user-images.githubusercontent.com/86715840/173807790-643e458f-b164-4865-a791-2fcb55d03f58.png)

When I use install.py script, lol in lutris can't start because have no executable.

**Comment by nhubaotruong** [comment]
You gotta install LOL first and then add the Executable manually or using the config script (which just find the executable and put it in for you). But right now I can't start LOL either, I'll get back to you when I find a way

**Comment by nhubaotruong** [comment]
@utbuiquoc Is there something else you need help with ? I see you reopen the issue

**Comment by utbuiquoc** [comment]
> @utbuiquoc Is there something else you need help with ? I see you reopen the issue

Sorry, my bad
