### ISSUE TITLE
Stuck on loading screen after launching the game via Garena

### ISSUE THREAD

**Issue by xruifan** [nhubaotruong/league-of-legends-linux-garena-script#43]
Hi, 

The client stuck on loading screen as the picture shown below. 
![Screenshot_20220620_103954](https://user-images.githubusercontent.com/74106382/174517522-f4e839eb-254b-433e-b517-20af238a6773.png)
 
The log: 
[log.txt](https://github.com/nhubaotruong/league-of-legends-linux-garena-script/files/8937203/log.txt)

Lutris Garena runner options:
![image](https://user-images.githubusercontent.com/74106382/174518011-be6078e6-d7de-403e-b429-9cbea346615e.png)
![image](https://user-images.githubusercontent.com/74106382/174518071-e7582c01-8619-4ca3-a231-7c6f03f4f2ee.png)
![image](https://user-images.githubusercontent.com/74106382/174518107-91760cfb-7553-4087-92ed-1907c4fdea61.png)

Lutris LOL runner options:
![image](https://user-images.githubusercontent.com/74106382/174518186-ae648690-e642-4523-89a7-7fbd79740247.png)
![image](https://user-images.githubusercontent.com/74106382/174518201-11a2e532-45dd-4e92-9b37-f25e3247b6d7.png)
![image](https://user-images.githubusercontent.com/74106382/174518254-624de99d-3d62-44cb-9d12-a2fa7e7a71a4.png)

System:
OS:              Debian GNU/Linux 11 bullseye
Arch:            x86_64
Kernel:          5.10.0-15-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            1.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 20.3.5
OpenGL Core:     4.6 (Core Profile) Mesa 20.3.5
OpenGL ES:       OpenGL ES 3.2 Mesa 20.3.5
Vulkan:          Supported

I am looking forward to your reply.
Fan

**Comment by longz3r** [comment]
same for me 
but my game will be not responding if chose RiotClientSerivces.exe in LOL lutris config
if LeagueClient.exe is selected will be like you

**Comment by xruifan** [comment]
> same for me but my game will be not responding if chose RiotClientSerivces.exe in LOL lutris config if LeagueClient.exe is selected will be like you

What I think is you use LeagueClient.exe as the executable if you belong to Asia as mentioned in [this](https://github.com/nhubaotruong/league-of-legends-linux-garena-script#the-garena-client-is-almost-exclusively-intended-for-asia-includes-south-south-east-east-etc-if-you-do-not-belong-to-the-aforementioned-regions-like-na-eu-etc-please-use-the-riot-client-instead-what-lutris-ships-by-default) section. If I get it wrong please let me know, thanks.

**Comment by longz3r** [comment]
> > same for me but my game will be not responding if chose RiotClientSerivces.exe in LOL lutris config if LeagueClient.exe is selected will be like you
> 
> What I think is you use LeagueClient.exe as the executable if you belong to Asia as mentioned in [this](https://github.com/nhubaotruong/league-of-legends-linux-garena-script#the-garena-client-is-almost-exclusively-intended-for-asia-includes-south-south-east-east-etc-if-you-do-not-belong-to-the-aforementioned-regions-like-na-eu-etc-please-use-the-riot-client-instead-what-lutris-ships-by-default) section. If I get it wrong please let me know, thanks.

Although i chose RiotClientServices.exe as metioned game will show league of legends splash screen and become not responding (will disappear after few minutes)

**Comment by nhubaotruong** [comment]
Can you guys please try again using wine lutris lol 7.0.1 and the injector script as I specified in the lol.json file ? It has been working for me

**Comment by 2ndBillGates** [comment]
> Can you guys please try again using wine lutris lol 7.0.1 and the injector script as I specified in the lol.json file ? It has been working for me

OK, I'll try it now. It didn't work for me either yesterday, I'm from Taiwan

**Comment by 2ndBillGates** [comment]
I was using wine lutris-ge-lol-7.0.2, my system is Fedora 36

**Comment by 2ndBillGates** [comment]
I still have to download lutris version LOL(US) for that to work, right?

**Comment by nhubaotruong** [comment]
```
lutris -i https://raw.githubusercontent.com/nhubaotruong/league-of-legends-linux-garena-script/main/lol.json
```
Just run this, it's my lol config

**Comment by 2ndBillGates** [comment]
![Screenshot from 2022-07-01 12-37-09](https://user-images.githubusercontent.com/60785205/176824304-0e1d5785-a326-4571-b6c8-80762d30edd6.png)
I run the lol.json install script you mentioned above, I'm still getting this loading screen.

**Comment by nhubaotruong** [comment]
Did you set the Executable to `RiotClientServices.exe` ?

**Comment by 2ndBillGates** [comment]
may executable path: /run/media/WD/Lol/32775/32775/LeagueClient/LeagueClient.exe

**Comment by nhubaotruong** [comment]
Set it to `{whatever_the_game_path}/Riot Client/RiotClientServices.exe`

**Comment by 2ndBillGates** [comment]
> Did you set the Executable to `RiotClientServices.exe` ?

I tried to set it to `RiotClientServices.exe` inside the Garena LOL installation folder.
"Lol/32775/32775/Riot Client/RiotClientServices.exe"

But when I launch it, nothing shows up

**Comment by nhubaotruong** [comment]
I'm not sure, I was using wayland so maybe it's different. But `RiotClientServices.exe` was the right thing, using `LeagueClient.exe` don't work anymore

**Comment by 2ndBillGates** [comment]
And If I set it to LOL(US)'s RiotClientServices.exe

I get the the Riot login screen for US
![Uploading Screenshot from 2022-07-01 12-44-26.png…]()

**Comment by 2ndBillGates** [comment]
> I'm not sure, I was using wayland so maybe it's different. But `RiotClientServices.exe` was the right thing, using `LeagueClient.exe` don't work anymore

I see But I'm using wayland as well

**Comment by nhubaotruong** [comment]
I mean set it to `RiotClientServices.exe` from the Garena installed LOL, not the default one :smile:

**Comment by 2ndBillGates** [comment]
> I mean set it to `RiotClientServices.exe` from the Garena installed LOL, not the default one smile

OK，If I set it to `RiotClientServices.exe` from the Garena installed LOL. Nothing is showing up.
I still have to use lol.py before pressing the Play button, right?

After I clicked play button, `LeagueClient.exe` process it's running in the background. But there is no window in the front.

**Comment by nhubaotruong** [comment]
Do you have the dependencies for `psutil` and `frida` installed for the launchscript ?

**Comment by 2ndBillGates** [comment]
I tried to run `python injector.py`

It gave me these

> Traceback (most recent call last):
  File "/home/tom/Games/league-of-legends/injector.py", line 70, in <module>
    signal.signal(signal.SIGBREAK, sigterm_handler)
AttributeError: module 'signal' has no attribute 'SIGBREAK'. Did you mean: 'SIGTRAP'?

**Comment by 2ndBillGates** [comment]
> Do you have the dependencies for `psutil` and `frida` installed for the launchscript ?

I believed I did

> Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: frida in /home/tom/.local/lib/python3.10/site-packages (15.1.27)
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (from frida) (59.6.0)

**Comment by 2ndBillGates** [comment]
Something different

I set Virtual Desktop enable, now `league of legends` LOGO shows in the `Virtual Desktop` but nothing more.

**Comment by 2ndBillGates** [comment]
I just installed KDE plasma, When I click play, this logo shows up and stuck in here
![Screenshot_20220701_141244](https://user-images.githubusercontent.com/60785205/176835065-abd4111c-d68d-4a2c-8a25-2ecad5e79d9a.png)
Maybe I missed installing something?

**Comment by khewweifeng** [comment]
> I just installed KDE plasma, When I click play, this logo shows up and stuck in here ![Screenshot_20220701_141244](https://user-images.githubusercontent.com/60785205/176835065-abd4111c-d68d-4a2c-8a25-2ecad5e79d9a.png) Maybe I missed installing something?

I also stuck here @2ndBillGates

**Comment by xruifan** [comment]
> Can you guys please try again using wine lutris lol 7.0.1 and the injector script as I specified in the lol.json file ? It has been working for me

Hi, thank you for your replies. I have tried to use `lutris-ge-lol-7.0-1-x86_64` and unfortunately nothing changed.

**Comment by nhubaotruong** [comment]
Hi guys, I've been trying with my friends computer, and it works for him too, I'm playing on Vietnam server. I'm playing on Arch Linux, I'm wondering if the distro is affecting anything. Can you guys share your distros ? I mostly use Arch so I'm not familiar with the dependencies name on other distros

**Comment by 2ndBillGates** [comment]
> Hi guys, I've been trying with my friends computer, and it works for him too, I'm playing on Vietnam server. I'm playing on Arch Linux, I'm wondering if the distro is affecting anything. Can you guys share your distros ? I mostly use Arch so I'm not familiar with the dependencies name on other distros

Hello there
I use arch before just recently switch to fedora. I wish I didn't make the switch.


Yesterday, I thought If TW Garena wouldn't work, then, NA server should work, right?

Then, I go ahead and start it, nothing shows up, I was very disappointed.


Later, I do it one more time in KDE PLASMA and use the newest wine 7.0.2-ge-lol

Guess what, NA server lol client successfully run and able to play. It seems GNOME unable to recognise boardless window like leagueclient.



ONLY a few problems,
1. In Full screen, mouse cannot click to control, have to set it to boardless mode in game.cfg

2. Whenever I try to use plasma overview or touch pad gesture, League of Legends crashes.

**Comment by 2ndBillGates** [comment]
I am going to test Garena LOL on KDE Plasma with 7.02-ge-lol wine and see if this is working

**Comment by khewweifeng** [comment]
> Hi guys, I've been trying with my friends computer, and it works for him too, I'm playing on Vietnam server. I'm playing on Arch Linux, I'm wondering if the distro is affecting anything. Can you guys share your distros ? I mostly use Arch so I'm not familiar with the dependencies name on other distros

Hi, 

I tried POP OS (ubuntu LTS 22.04) and MX LINUX KDE (debian 11) 

MX LINUX can show logo without prompting leagueclient not responding message like this https://github.com/nhubaotruong/league-of-legends-linux-garena-script/issues/43#issuecomment-1171977101

**Comment by khewweifeng** [comment]
> I am going to test Garena LOL on KDE Plasma with 7.02-ge-lol wine and see if this is working

It does not work from my end 😢 I tried 7.02 and 7.01 also having same result

**Comment by 2ndBillGates** [comment]
Hey guys, you mentioned `injector.py` script in some comment.


But how do I run the script, I try to run by `python injector.py` and I gave me some error.

I set up the pre-run script in the lutris setting, and run Garena /luris lol, nothing happens.

I haven't been able to get a prompt and ask me to give root password, root permission, no matter what I do. 


How do I debug in the terminal.

The only method I know was to run lutris in terminal

**Comment by 2ndBillGates** [comment]
Probably, a TW Garena issue?

Seems most of us who has the `no graphics problem with lolclient ` are  TW server players

**Comment by khewweifeng** [comment]
> Probably, a TW Garena issue?
> 
> Seems most of us who has the `no graphics with lolclient problem ` are TW server players

I am SG server but I think it should be the same because TW also using garena client to launch the game

**Comment by khewweifeng** [comment]
![image](https://user-images.githubusercontent.com/54496743/176987016-35071367-84ae-4ebb-8cad-67690ac6996f.png)

**Comment by nhubaotruong** [comment]
Okay guys, finally figure out what's wrong, In the launch script I have these lines
```bash
if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
    exit 0
fi
pkexec sh -c 'sysctl -w abi.vsyscall32=0'
```
which changes the kernel's parameter `abi.vsyscall32` to `0` for the game to start

It used to be that both the client and the actual gameplay can work if this parameter is set to `0`, but now the client can only start when it's `1` and the gameplay can only start if it's `0`

Please try comment out the line in `launchhelper2.sh` like so
```bash
#!/usr/bin/env sh

if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
    exit 0
fi

#pkexec sh -c 'sysctl -w abi.vsyscall32=0'

python launchhelper2.py
```
When the client start, manually run `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` before you start a game, if it works for you I'll update the repo

**Comment by 2ndBillGates** [comment]
> ![image](https://user-images.githubusercontent.com/54496743/176987016-35071367-84ae-4ebb-8cad-67690ac6996f.png)

 Mines too, first it's black then when things are loaded, colours are back
1 minute after that, it disappeared and that's it.
![Screenshot_%Nd_2022-07-02_15,41,34](https://user-images.githubusercontent.com/60785205/176991609-8c86497a-7f6d-4ef2-be88-e4d46d75084d.jpg)


![Screenshot_%Nd_2022-07-02_14,48,34](https://user-images.githubusercontent.com/60785205/176991511-4d835619-0a58-497e-9389-e12d750bec57.jpg)

no prompt for password or anything

**Comment by khewweifeng** [comment]
> Okay guys, finally figure out what's wrong, In the launch script I have these lines
> 
> ```shell
> if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
>     exit 0
> fi
> pkexec sh -c 'sysctl -w abi.vsyscall32=0'
> ```
> 
> which changes the kernel's parameter `abi.vsyscall32` to `0` for the game to start
> 
> It used to be that both the client and the actual gameplay can work if this parameter is set to `0`, but now the client can only start when it's `1` and the gameplay can only start if it's `0`
> 
> Please try comment out the line in `launchhelper2.sh` like so
> 
> ```shell
> #!/usr/bin/env sh
> 
> if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
>     exit 0
> fi
> 
> #pkexec sh -c 'sysctl -w abi.vsyscall32=0'
> 
> python launchhelper2.py
> ```
> 
> When the client start, manually run `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` before you start a game, if it works for you I'll update the repo

this time it did prompted to enter password but still stuck at logo , after 5 min ... the game auto close

**Comment by khewweifeng** [comment]
> > Okay guys, finally figure out what's wrong, In the launch script I have these lines
> > ```shell
> > if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
> >     exit 0
> > fi
> > pkexec sh -c 'sysctl -w abi.vsyscall32=0'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which changes the kernel's parameter `abi.vsyscall32` to `0` for the game to start
> > It used to be that both the client and the actual gameplay can work if this parameter is set to `0`, but now the client can only start when it's `1` and the gameplay can only start if it's `0`
> > Please try comment out the line in `launchhelper2.sh` like so
> > ```shell
> > #!/usr/bin/env sh
> > 
> > if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
> >     exit 0
> > fi
> > 
> > #pkexec sh -c 'sysctl -w abi.vsyscall32=0'
> > 
> > python launchhelper2.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When the client start, manually run `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` before you start a game, if it works for you I'll update the repo
> 
> this time it did prompted to enter password but still stuck at logo , after 5 min ... the game auto close

Running /home/acer/.local/share/lutris/runners/wine/lutris-ge-lol-7.0-2-x86_64/bin/wine /home/acer/Games/garena/drive_c/Program Files (x86)/Garena/Garena/Garena.exe
Initial process has started with pid 2520
Start monitoring process.
esync: up and running.
ATTENTION: default value of option mesa_glthread overridden by environment.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

ATTENTION: default value of option mesa_glthread overridden by environment.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

wine: Call from 7BC2F920 to unimplemented function dxgi.dll.DXGID3D10CreateDevice, aborting
ATTENTION: default value of option mesa_glthread overridden by environment.
wine: Call from 7BC2F920 to unimplemented function dxgi.dll.DXGID3D10CreateDevice, aborting
ATTENTION: default value of option mesa_glthread overridden by environment.
wine: Call from 7BC2F920 to unimplemented function dxgi.dll.DXGID3D10CreateDevice, aborting
[0702/164627:ERROR:network_change_notifier_win.cc(153)] WSALookupServiceBegin failed with: 8
ATTENTION: default value of option mesa_glthread overridden by environment.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

wine: Call from 7BC2F920 to unimplemented function dxgi.dll.DXGID3D10CreateDevice, aborting
wine: Unimplemented function dxgi.dll.DXGID3D10CreateDevice called at address 7BC2F920 (thread 02a8), starting debugger...
Unhandled exception: unimplemented function dxgi.dll.DXGID3D10CreateDevice called in segmented 32-bit code (0107:7bc2f920).
Assertion failed: curr_mode == stm_32bit, file /home/ubuntu/buildbot/runners/wine/wine-src/dlls/dbghelp/cpu_i386.c, line 278

[0702/164652:ERROR:ipc_channel_win.cc(502)] pipe error: 232
Caught signal 15
passing along signal to PID 2520
passing along signal to PID 2531
passing along signal to PID 2596
passing along signal to PID 2855
passing along signal to PID 3250
passing along signal to PID 3265
--terminated processes--
Monitored process exited.
Initial process has exited (return code: 15)
All monitored processes have exited.
Exit with returncode 15

**Comment by 2ndBillGates** [comment]
> 

I've got similar result 


> 046c:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (158BF590 1 C) semi-stub
> 0470:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (167CFD58 1 C) semi-stub
> 0180:err:ole:CoUninitialize Mismatched CoUninitialize
> 0270:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (01C6DA20 1 C) semi-stub
> 027c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0069FEAC
> 0188:err:ole:CoUninitialize Mismatched CoUninitialize
> 
> 0114:fixme:font:NtGdiRemoveFontMemResourceEx (0x74fdd331) stub
> 0114:fixme:font:NtGdiRemoveFontMemResourceEx (0x74512331) stub
> 0114:fixme:font:NtGdiRemoveFontMemResourceEx (0x746f7331) stub
> 0114:fixme:font:NtGdiRemoveFontMemResourceEx (0x755c1331) stub
> 0114:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 047DFE98
> 0140:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 007EFE98
> Monitored process exited.
> Initial process has exited (return code: 0)
> Exit with return code 0
> 2022-07-02 17:12:07,213: Game still running (state: running)
> 2022-07-02 17:12:07,213: Stopping League of Legends (wine)

**Comment by 2ndBillGates** [comment]
But I don't have a prompt for password though

**Comment by nxhdev2002** [comment]
> Okay guys, finally figure out what's wrong, In the launch script I have these lines
> 
> ```shell
> if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
>     exit 0
> fi
> pkexec sh -c 'sysctl -w abi.vsyscall32=0'
> ```
> 
> which changes the kernel's parameter `abi.vsyscall32` to `0` for the game to start
> 
> It used to be that both the client and the actual gameplay can work if this parameter is set to `0`, but now the client can only start when it's `1` and the gameplay can only start if it's `0`
> 
> Please try comment out the line in `launchhelper2.sh` like so
> 
> ```shell
> #!/usr/bin/env sh
> 
> if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
>     exit 0
> fi
> 
> #pkexec sh -c 'sysctl -w abi.vsyscall32=0'
> 
> python launchhelper2.py
> ```
> 
> When the client start, manually run `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` before you start a game, if it works for you I'll update the repo

![image](https://user-images.githubusercontent.com/22050271/176994674-e8bf0a18-55a8-4282-b443-c444cb6874f6.png)
It's work for me. I thought i would go back to windows but it worked, fps was high and can enjoy the game. thank you

**Comment by khewweifeng** [comment]
> > Okay guys, finally figure out what's wrong, In the launch script I have these lines
> > ```shell
> > if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
> >     exit 0
> > fi
> > pkexec sh -c 'sysctl -w abi.vsyscall32=0'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which changes the kernel's parameter `abi.vsyscall32` to `0` for the game to start
> > It used to be that both the client and the actual gameplay can work if this parameter is set to `0`, but now the client can only start when it's `1` and the gameplay can only start if it's `0`
> > Please try comment out the line in `launchhelper2.sh` like so
> > ```shell
> > #!/usr/bin/env sh
> > 
> > if [ "$(cat /proc/sys/abi/vsyscall32)" -eq 0 ]; then
> >     exit 0
> > fi
> > 
> > #pkexec sh -c 'sysctl -w abi.vsyscall32=0'
> > 
> > python launchhelper2.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When the client start, manually run `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` before you start a game, if it works for you I'll update the repo
> 
> ![image](https://user-images.githubusercontent.com/22050271/176994674-e8bf0a18-55a8-4282-b443-c444cb6874f6.png) It's work for me. I thought i would go back to windows but it worked, fps was high and can enjoy the game. thank you

Congrats @nxhdev2002 , may I know what linux distro you using ?

**Comment by 2ndBillGates** [comment]
damn, congrats man

**Comment by 2ndBillGates** [comment]
I'm using Surface Book 2(i7,GTX1060, 16GB Ram), Fedora 36, kernel 5.18.7

**Comment by 2ndBillGates** [comment]
> pkexec sh -c 'sysctl -w abi.vsyscall32=1

holy shxt, my man
it's working

you guys are amazing

**Comment by 2ndBillGates** [comment]
I love you guyz mN

**Comment by 2ndBillGates** [comment]
Been happy to working with you guys

![Screenshot_%Nd_2022-07-02_19,27,23__Spectacle_EDITED](https://user-images.githubusercontent.com/60785205/176999148-2bc3806a-7b0a-450f-8a44-046cfc1ca039.png)

**Comment by xruifan** [comment]
> When the client start, manually run `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` before you start a game, if it works for you I'll update the repo

It looks like everything works fine now. I am closing this issue and I think you could update this repo.

**Comment by 2ndBillGates** [comment]
gotta say the performance was better than i expected.

I'm getting 200fps initially, now running 60fps stable at 1366x768, mid settings

**Comment by 2ndBillGates** [comment]
you just gotta set the screen to boardless, else the mouse will move out of the window

**Comment by 2ndBillGates** [comment]
just finished an ARAM round with Riven, gotta say the performance is really good, no lag at all.

But
the keyboard works really weird though, when I press q sometimes it does not respond and sometimes it press 2 times.

But that kind of performance, I take it.

FOREVERLY LEAVE rubbish WINDOWS

**Comment by 2ndBillGates** [comment]
> 

I am using english keyboard, us layout

I can reproduce it easily. when i click enter to open chat box, it never opens, it clicks 2 times, open and close it

**Comment by khewweifeng** [comment]
> i ran "pkexec sh -c 'sysctl -w abi.vsyscall32=1'", lol.py and then pressed the play button in garena, but it took a while for the client to work, i tried with wine lutris-ge-lol-7.0.1 . if you want to connect to the match, you must set abi.vsyscall32=0

Hi @nxhdev2002  have to do it everytime or only 1 time ?

**Comment by khewweifeng** [comment]
> > > i ran "pkexec sh -c 'sysctl -w abi.vsyscall32=1'", lol.py and then pressed the play button in garena, but it took a while for the client to work, i tried with wine lutris-ge-lol-7.0.1 . if you want to connect to the match, you must set abi.vsyscall32=0
> > 
> > 
> > Hi @nxhdev2002 have to do it everytime or only 1 time ?
> > ![image](https://user-images.githubusercontent.com/22050271/177004792-cdf35d2d-984e-4157-977f-63824c6bb2a3.png)
> > I have to do it everytime, otherwise the client won't respond. i think we should wait for repo update

@nhubaotruong

**Comment by longz3r** [comment]
do i have to use lol.py with abi.vsyscall=1 or just use garena launch game directly ?

**Comment by nhubaotruong** [comment]
@khewweifeng It has to be done every time you start LOL client
@longz3r Please use the `lol.py` with `abi.vsyscall=1`

**Comment by khewweifeng** [comment]
> @khewweifeng It has to be done every time you start LOL client @longz3r Please use the `lol.py` with `abi.vsyscall=1`

will you update into appimage / the repo ?

**Comment by nhubaotruong** [comment]
Yes I will, trying to figure out how to make it more convenient for you guys

**Comment by longz3r** [comment]
![image](https://user-images.githubusercontent.com/81682520/177065297-afd52956-2b7c-4ab4-bad3-1b8de506aace.png)
Splash screen will get color after it but it will disappear with abi.vsyscall=1 and lol.py

**Comment by khewweifeng** [comment]
I edited launchhelper2 and use lol.py

![Screenshot from 2022-07-06 11-54-14](https://user-images.githubusercontent.com/54496743/177464851-6a7b64f8-76fa-4c2d-aaa3-61747a81822d.png)

and the game stuck here 
![Screenshot from 2022-07-06 11-56-20](https://user-images.githubusercontent.com/54496743/177464975-86e4cb79-f63f-42c9-82a4-f3bf9f25c81b.png)
![Screenshot from 2022-07-06 11-53-49](https://user-images.githubusercontent.com/54496743/177464980-768abca8-0331-455c-9544-94cd956767fc.png)

**Comment by khewweifeng** [comment]
tried garena with lutris lol 7.0.1 = garena app will show flickering

**Comment by xruifan** [comment]
> I edited launchhelper2 and use lol.py with lutris lol 7.0.1

@khewweifeng 
Hi, please accept my apologies for the late reply. Have you fixed the issue? If not, could you try to comment out the line `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` in `launchhelper2.sh` and directly run `pkexec sh -c 'sysctl -w abi.vsyscall32=1'` before you run `lol.py` and start league? Don't forget to run `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` before any match starts.

**Comment by khewweifeng** [comment]
> > I edited launchhelper2 and use lol.py with lutris lol 7.0.1
> 
> @khewweifeng Hi, please accept my apologies for the late reply. Have you fixed the issue? If not, could you try to comment out the line `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` in `launchhelper2.sh` and directly run `pkexec sh -c 'sysctl -w abi.vsyscall32=1'` before you run `lol.py` and start league? Don't forget to run `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` before any match starts.

I think it does not work with Intel graphics

**Comment by khewweifeng** [comment]
how about this part ? 

![Screenshot_20220716_130618](https://user-images.githubusercontent.com/54496743/179340282-5703e4c3-dd0a-4557-b229-43bd1fb6c107.png)

**Comment by khewweifeng** [comment]
somtimes it will be redirected to riot games lol

**Comment by longz3r** [comment]
im tired of trying get it working
im going for dualboot windows 10 ghost spectre and debian

**Comment by xruifan** [comment]
> how about this part ?
> 
> ![Screenshot_20220716_130618](https://user-images.githubusercontent.com/54496743/179340282-5703e4c3-dd0a-4557-b229-43bd1fb6c107.png)

I think you would need to set it to run league, just click yes. 

In my experience, I need to run many times of `pkexec sh -c 'sysctl -w abi.vsyscall32=1'`, `lol.py`, and click play in Garena to get the league client start normally. I am not sure if it has something to do with `lanchhelper.sh` in league that deals with ssh and timeout stuff, you will need to be patient with it. 

In addition, in my way of understanding what is going on, I would start lutris with `lutris -d` to keep tracking the process, Garena runs pretty badly on linux.

**Comment by simon2323** [comment]
Commenting out `pkexec sh -c 'sysctl -w abi.vsyscall32=0'` and specify `python3 launchhelper2.py` worked for me.

I'm on Ubuntu 20.04 and I have both python2 and python3 on my system.
Running `pkexec sh -c 'sysctl -w abi.vsyscall32=1'` does fix the problem after the patch, but I'd only get the client to launch with a success rate of 1/20 or 1/30. Otherwise it'd be like what @longz3r experienced.

**Comment by 2ndBillGates** [comment]
> > how about this part ?
> > ![Screenshot_20220716_130618](https://user-images.githubusercontent.com/54496743/179340282-5703e4c3-dd0a-4557-b229-43bd1fb6c107.png)
> 
> I think you would need to set it to run league, just click yes.
> 
> In my experience, I need to run many times of `pkexec sh -c 'sysctl -w abi.vsyscall32=1'`, `lol.py`, and click play in Garena after the client fails in lutris log, to get the league client start normally. I am not sure if it has something to do with `lanchhelper.sh` in league that deals with ssh and timeout stuff, you will need to be patient with it.
> 
> In addition, in my way of understanding what is going on, I would start lutris with `lutris -d` to keep tracking the process, Garena runs pretty badly on linux.

for me, i press no everytime and it works.
BTW, i'm using lutris lol 7.0.2
