### ISSUE TITLE
Unable to join queue

### ISSUE THREAD

**Issue by rocielrociel** [nhubaotruong/league-of-legends-linux-garena-script#6]
So I followed the instructions and LoL started correctly but says that it cannot join the queue and quits.

This is the (modified) code I ran: https://pastebin.pl/view/716d5924

This is the output after running the script:
`--garena-plus-token=at7gIBCMKrC/W0sCP6RApL2/YtbU5oJ8LRbLhqOoPkGWLfksmhHgrka7oTIx1g1dAvadHTEkADCA7uEhc0kJ1rp5Zq5E8GIi/0NfdBRC4NdKg5HkSO6LsITelwAsXZL2ag39u0P2EsCQuCo6KuFVXQIjswLdMs8Ti829EPU1PeQxxWHAdCwYOkcEdqItzKB94QgH4KdS2FDvl0LhP0JaR62K8otxCirnZA7ywbU9BsDpXVZhDZHWUv6XiOkrYC/7Ywzv4SiD+b1svlNpTfTtlnLzdHoXeK5MqBfs5ev9d3BdKPS0U1yinBuypKO6oMZ6X0XRqRk/UBuEPZ6t2cMFiQ== --region=TW -- --locale=zh_TW --landing-token=a8a8c21c120512a4e886927486d15d90bf26e20d6a3ac9dc972a66e338f8ac60 --servers.chat.chat_host=tw1.chat.si.riotgames.com --servers.lcds.lcds_host=prodtw1.lol.garenanow.com --servers.lcds.login_queue_url=https://lqtw1.lol.garenanow.com/login-queue/rest/queues/lol --region=TW --parent-client=GarenaPC`

I have no idea what any of this means so I figured I'd ask for help. Thanks in advance.

**Comment by rocielrociel** [comment]
aaand the formatting decides to not work for some reason. But I think you get the point.

**Comment by nhubaotruong** [comment]
If you're using lutris then this part won't be needed in the script though
```
launchhelper = "/home/rociel/Games/league-of-legends/launchhelper.sh"
WINEPREFIX = "/home/rociel/Games/league-of-legends"

game_path = "/media/rociel/LinuxGames/LutrisGames/garena/drive_c/Garena/Games/32775/Riot Client/RiotClientServices.exe"

wine_exe = (
"/home/rociel/.local/share/lutris/runners/wine/lutris-lol-5.5-2-x86_64/bin/wine"
)

use_gamemoderun = True

use_esync = True

use_fsync = True
```
Try changing the Executable in LOL lutris config to `<Game path>/Riot Client/RiotClientServices.exe` then login again, previously I was using `RiotClientServices.exe`, it will take longer to start the game, but seems more stable

**Comment by rocielrociel** [comment]
Well it did load for several minutes this time, which from what I understand is what's supposed to happen. But then it hit me with the unknown error while connecting and closes again.

Here's the code I ran https://pastebin.pl/view/1c7f9932

**Comment by nhubaotruong** [comment]
Oh, sometimes it will have unknown error, and then after a while the game will return at the exact same state when it crashes. Can you give me the lutris log ?

**Comment by rocielrociel** [comment]
Garena logs： https://pastebin.pl/view/347fb664

LoL logs: https://pastebin.pl/view/1bc05db8

**Comment by nhubaotruong** [comment]
the LOL log seems too short, Can you tell me what system are you using and have you installed the dependencies ?

**Comment by rocielrociel** [comment]
I'm running OpenSUSE Tumbleweed and I think I have everything... maybe.

**Comment by nhubaotruong** [comment]
Well, I haven't used OpenSUSE yet, does it support 32bit libraries ?

**Comment by rocielrociel** [comment]
I think it does. Steam is 32bit and that works fine.

**Comment by nhubaotruong** [comment]
It's pretty hard to debug, can you do a screen record of you launching the game, with the lutris log of LOL open ?

**Comment by rocielrociel** [comment]
Here it is. https://youtu.be/DZ1HF-HUTc4

**Comment by nhubaotruong** [comment]
Oh, I see the problem, the old LOL process is still running, open Process manager and kill all `Riot` and `League` related process then try again

**Comment by rocielrociel** [comment]
ok I found the problem now. Thanks for the help!
