### ISSUE TITLE
Can't open LoL

### ISSUE THREAD

**Issue by PotatoAim2001** [nhubaotruong/league-of-legends-linux-garena-script#7]
Hello, can you help me with this problem?
![prob](https://user-images.githubusercontent.com/89135304/129884518-064a54bf-2cf3-4c7a-b36d-d0e4fec328ac.png)

**Comment by nhubaotruong** [comment]
Looks like there are more than 1 config file in there, can you take a look in `~/.config/lutris/games` and check

**Comment by PotatoAim2001** [comment]
![prob](https://user-images.githubusercontent.com/89135304/129894883-c66afb7b-2655-4b80-aa02-d2e32b167ad4.png)

**Comment by nhubaotruong** [comment]
I just updated the script to better handle getting league config file, please download the latest version and try again

**Comment by PotatoAim2001** [comment]
Thanks man it works! BTW Did I put lol.py in the right file? 
![Screenshot from 2021-08-18 20-51-22](https://user-images.githubusercontent.com/89135304/129901380-c475b63a-30b6-44b3-9655-002f833fe371.png)

**Comment by nhubaotruong** [comment]
You can put it anywhere, I do path resolving in the code already, no relative path here

**Comment by PotatoAim2001** [comment]
Ah okay, last question, should I just click 'x' to exit League and terminal safely? 

ps. I'm bad at my english. sorry.

**Comment by nhubaotruong** [comment]
I'm not sure what you mean here, the scripts end when it launches LOL, so you can just close the terminal now, and interact with LOL from GUI

**Comment by PotatoAim2001** [comment]
Ah okay, Thank you so much for your effort

**Comment by nhubaotruong** [comment]
Happy gaming !
