### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by Codiecher** [nhubaotruong/league-of-legends-linux-garena-script#8]
![image](https://user-images.githubusercontent.com/49608838/131122347-fc6f4faf-128e-460e-9020-f36c075464f4.png)

worked last time, this is after using the new .py file

**Comment by nhubaotruong** [comment]
@Codiecher Hey, I think LOL got broke after the 11.17 update, please try updating to new wine-lol version (added in README) and try start the game again

**Comment by Codiecher** [comment]
![image](https://user-images.githubusercontent.com/49608838/131254191-a77f4c5c-95df-438b-8f01-6cb76aec9322.png)

Just saw this new wine version, I'll try this one first before I try the fix

**Comment by nhubaotruong** [comment]
Oh, I found the other wine this afternoon, now lutris got updated as well

**Comment by nhubaotruong** [comment]
The game fail to start with `lutris-ge-lol-6.15` for me. How about you ?

**Comment by Codiecher** [comment]
![image](https://user-images.githubusercontent.com/49608838/131255481-c805e951-b207-4624-a27e-311b97717d50.png)

it worked perfectly

**Comment by Codiecher** [comment]
![image](https://user-images.githubusercontent.com/49608838/131255505-79608854-f838-45a6-b93f-3eb23bc7f315.png)

worked perfectly for me!

**Comment by Codiecher** [comment]
![image](https://user-images.githubusercontent.com/49608838/131255694-219a4d61-cf46-4546-8c20-b0e9baa62936.png)

**Comment by Codiecher** [comment]
Good to hear, Imma close this now
