### ISSUE TITLE
client won't show up

### ISSUE THREAD

**Issue by Lucentaust** [nhubaotruong/league-of-legends-linux-garena-script#9]
`python3 lol.py                                            ✔  4s  
The script will wait for a RiotClientServices.exe process to show up to get it's token. So go to the Garena client and press Play
Garena token got from RiotClientServices.exe: --garena-plus-token=iszG/wKdP1xGEVFthnVMAtwyAmyQ7cJiETwJAy0oe7KXO/x78ciSX6iyHPcQvJz54zChhcuTQ7EvG4E/CQ7LY+UTaP9YxmMtpU05978s2VBO+uv4kepyX61Er7AQimIt9NyzsHZrcGjPBzAI9CmKl92+zV0YsbubIcmnaxzztsaUQVTdfufruE+3sJMncXzOB4N+iV7cwGxx0BM8IZEmllU1zE1KEb+5TrdC0AZOCeUGSV2mFf5FE2NvXzGYZWiSgRlagikveIsekXSbaG1YpXpFvgPWhsAoTAGfcNS2z4OMAzCDW44z7V+i1cXQmXlOiHr20R7h79b0aWBN7TrO4g== --region=TH -- --locale=th_TH --landing-token=da59f07d69f4fc7e690cda3206fac18a3b37c0cbb4f07ba51333e53a1d405b49 --servers.chat.chat_host=th1.chat.si.riotgames.com --servers.lcds.lcds_host=prodth.lol.garenanow.com --servers.lcds.login_queue_url=https://lqth.lol.garenanow.com/login-queue/rest/queues/lol --region=TH --parent-client=GarenaPC
Starting game with current config:
- Wine version: lutris-lol-5.5-2-x86_64
- Executable: /home/lucentaust/Games/garena/drive_c/Garena/Games/32786/LeagueClient/LeagueClient.exe
- Wineprefix: /home/lucentaust/Games/league-of-legends
If this is your first time running LOL since reboot, a pop up will appear, chose the first or second option then enter your password

It's a workaround by the lutris community

Ignore the lines below, they are not actually error

2021-08-29 10:30:52,445: No cores found
`
after i ran the script, It show only LoL logo. how to fix it??

**Comment by nhubaotruong** [comment]
The latest LOL update broke LOL on Linux, I'm trying out some workaround for now. It's apparently fixed in newer version of wine, but the lutris-lol is still wine 5.5 so it won't work. Please hang on and I'll comeback with some replies

**Comment by Lucentaust** [comment]
ok, thank u for your reply.

**Comment by nhubaotruong** [comment]
Please check the README, I've added a new session for updating to a new wine-lol version that can play the game

**Comment by nhubaotruong** [comment]
Hi @Lucentaust Have you check it yet ?

**Comment by VihagChaturvedi** [comment]
better to close the ticket ig ¯\_(ツ)_/¯

**Comment by nhubaotruong** [comment]
@Lucentaust Close for not having response in a long time. If you have anything new, please reopen this issue
